spring:
  rabbitmq:
    host: 192.168.138.54
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual  #����ack
    publisher-confirms: true #��������ȷ��
    publisher-returns: true #��������ʧ�ܷ���



